language: node_js
node_js:
- node
- '4.1'
- '4.0'
sudo: false
os:
- linux
- osx
matrix:
  fast_finish: true
  allow_failures:
  - os: osx
env:
- NODE_ENV=test
install:
- npm install
before_script:
- node maid.js
deploy:
  provider: npm
  email: madisontries@gmail.com
  api_key:
    secure: AMQGEmhn1b3mQyQ33xlIzKSCgs3JRTNjf8/TXanXI3hXwWDHZjKIvr8iJHCoon6JGP0/B8FCcMoH4tzTSl98ZVZUrsou75FN3ynIx5LB8nKZMZts3BehutXRECrP3NRUl4YPnJXeA4EeAYx+h3G/KEaOAosEWNKNxCEYqYdyJf4=
  on:
    repo: Phalanxia/Maid-IRC
